### ISSUE TITLE
cropped axis labels in 1D plot

### ISSUE THREAD

**Issue by photoniker** [itom-project/itom#152]
The label of a 1D plot with legendTitles is cropped even if only one character is included. This is not the case in the bright theme mode of itom. 

![](https://bitbucket.org/repo/jk4xbX/images/119713639-image.png)
![](https://bitbucket.org/repo/jk4xbX/images/1996153171-image.png)
‌

[Issue created by Johann Krauter: 2021-03-18]
[Last updated on bitbucket: 2022-07-08]

[Comment created by Bernd Bertschinger: 2022-07-08]
Interesting.

If that ist the Outcome. I am still very happy. ^^
I hope that the Student can lesen Something about the Qt classes and Widget structures.

But I'll check beforehand.

I don't want to frustrate them and then it nicht be better If they start w. some Demos and Tests and maybee some Plugins.

Thanks alot,

Bernd

[Comment created by Johann Krauter: 2022-07-08]
seems to bei a QT Bug. I don't know If a student can solve this...

[Comment created by Bernd Bertschinger: 2022-07-08]
Issue persists in v.4.2.0

![](https://bitbucket.org/repo/jk4xbX/images/4060053093-grafik.png)
Set kind to bug and Version to 5.0  
  
Johannes, do you have time and resources to finish the issue. As mentioned in the chat today I plan to hire some  
students and those minor tasks are ideal to get to know ITOM and it’s structure.  
  
Sincerely Yours,  
  
Bernd

**Comment by magro11** [comment]
Bernd Bertschinger

    changed version to [4.2.1](https://bitbucket.org/itom/itom/issues?version=4.2.1)

    2022-07-08

Johann Krauter reporter

seems to bei a QT Bug. I don't know If a student can solve this...

    Pin to top
    Mark as spam
    Delete
    2022-07-08

Bernd Bertschinger

Interesting.

If that ist the Outcome. I am still very happy. ^^ I hope that the Student can lesen Something about the Qt classes and Widget structures.

But I'll check beforehand.

I don't want to frustrate them and then it nicht be better If they start w. some Demos and Tests and maybee some Plugins.

Thanks alot,

Bernd
