### ISSUE TITLE
Pyside2 module not running w. ITOM

### ISSUE THREAD

**Issue by photoniker** [itom-project/itom#256]
Hi there,  
i just found that pyside2 supports some sort of singal/slot mechanics for python, [check this out](https://wiki.qt.io/Qt_for_Python_Signals_and_Slots).

Would this be possible for itom or is this a too major change?

**Comment by magro11** [comment]
See: https://bitbucket.org/itom/itom/issues/160/pyside2-module-not-running-w-itom
