### ISSUE TITLE
itom 4.30-dev: first test errors

### ISSUE THREAD

**Issue by anruedi** [itom-project/itom#293]
Hey zusammen,

ich hab mal ein paar Fehlerchen gesammelt, die mir aufgefallen sind:

1.     im Namen von itom im Explorer steht noch Version 4.2.2 anstatt 4.3
2.     es gibt Probleme mit der Vervollständigung. 
![grafik](https://github.com/itom-project/itom/assets/172780977/a1ed46a5-3382-42ce-829a-57c8c33e9e08)
3.     beim Debug-Modus kommt immer erstmal eine Fehlermeldung (beim ersten mal ist itom dann auch abgestürzt, die anderen Male konnte man durch nochmal klicken dann debuggen) 
![grafik](https://github.com/itom-project/itom/assets/172780977/1bc7b940-684d-4fd8-a058-094e921c7bb4)
 4.     Hat vielleicht nichts mit itom zu tun: Insgesamt gibt es Probleme bei der Matplotlib, dass er da irgendwas nicht findet:
![grafik](https://github.com/itom-project/itom/assets/172780977/546d18eb-d20e-4497-9596-4361a28bc506)
    Allerdings finde ich im Internet keine ähnliche Fehlermeldung und wenn man eine neue Matplotlib Version installiert, kommt es immer noch. Das gesucht "mplDeprecation" gibt es auch irgendwie wirklich nicht, aber ich frage mich, warum es jetzt plötzlich nicht mehr tut, wenn es bei den anderen Matplotlibs in den anderen itom Versionen und VSC ganz normal tut (auch wenn die betroffenen Matplotlib Datei gleich aussehen)

Das erfreuliche zum Schluss, dass Raptor Paket scheint zu tun. Ich konnte es einfügen und man kann eine Kamerainstanz anlegen und auch Bilder aufnehmen. Mehr habe ich noch nicht getestet. 🎉

Viele Grüße,
Andrea

**Comment by anruedi** [comment]
@BBertschinger

**Comment by BBertschinger** [comment]
Hi,

ich versuche gerade deine Fehlermeldungen nach zu vollziehen:
Jedi und Parso sind Bestandteil der All_in_One Packete und 

Ich kann auf dem Build-Server Breakpoints setzen und auch ohne Probleme ausführen.

Dasselbe gilt auch für die Matplotlib.

Es ist komisch, dass deine Itom Python Version bei deinem Itom v4.2.2 zu sein scheint.

**Comment by BBertschinger** [comment]
Das Problem ist ein Installer Problem,

wenn bereits Itom installiert wurde (v4.2.2), dann wird die neue Version v4.3.0 im selbern Verzeichnis, wie die vorherige installiert.
Die Auswahl eines abweichenden Installationsverzeichnis, oder das für diese Version gültige Default-Verzeichnis wird nicht angenommen.

Die bestehende Python Version wird jedoch nicht überschrieben. Daher kommt es zu den oben beschriebenen Konflikten.

Wird ITOM zunächst deinstalliert und dann eine neue Version installiert funktioniert alles ohne Probleme.

**Comment by BBertschinger** [comment]
Fixed the problem.
Changed the InnoSetup App-ID to include also the itom Version number and special identifiers.

Now each version is installed in a seprate directory.
