### ISSUE TITLE
F9 execution of scirpt lines

### ISSUE THREAD

**Issue by photoniker** [itom-project/itom#302]
The following script can of course be executed without any problems.

`mot = actuator("DummyMotor")

for _idx in range(5):
    pos = 1
    mot.setPosRel(0, pos)
    #
`

But If the for loop is marked and executed by **F9** a SyntaxError is shown in command line: 

`>>for _idx in range(5):
    pos = 1
    mot.setPosRel(0, pos)
    #
  File "<string>", line 4
    #
SyntaxError: invalid syntax
`

![image](https://github.com/user-attachments/assets/3a6b0494-cb07-47d0-a31c-2f1164eab37e)

**Comment by magro11** [comment]
The python interpreter does not accept to execute a single command, which is a comment only and it seems, that a comment in the last line is also not accepted. This is not only about F9 executions, but also when the command is run or debugged from the command line. In the latter case, an empty line will be appended before executing it.
